apiVersion: v2
name: space-taco
description: 🌮🚀 Intergalactic Taco Delivery Microservice
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - taco
  - microservice
  - gitops

maintainers:
  - name: your-org
    email: platform@your-org.com

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial intergalactic launch
